baseURL: "https://zhangyuan.netlify.app/"
title: zhang远
theme: PaperMod
paginate: 5

params:
  env: production
  author: Me
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  favicon: "/static/img/Beericons.svg"

  socialIcons:
    - name: github
      url: "https://github.com/"

  showBreadCrumbs: true
  showReading: true
  showShareButtons: false
  ShowPostNavLinks: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # 配置欢迎页
  profileMode:
    enabled: true # needs to be explicitly set
    title: "日常笔记"
    subtitle: "hugo搭建的笔记网站，想了解，去官网：https://gohugo.io/"
    imageUrl: "img/head.jpg"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Tech
        url: /posts/
      - name: blog
        url: "http://43.138.56.20"
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30


